# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
          WHO_TO_TRUST1: ${{'${WHO_TO_TRUST}'=='VALUE'}}
          TEST_ENV_VARIABLE: "testenvvariablevalue"
          booleannumcheck: ${{1==1}}
          booleanCharcheck: ${{'1'=='1'}}
          booleanconditionStringCheck: ${{'${WHO_TO_TRUST}'=='VALUE'}}
      
        
        run: echo "secret working---> ${WHO_TO_TRUST} and ${WHO_TO_TRUST1} and ${booleannumcheck}and ${booleanCharcheck} and ${booleanconditionStringCheck} and test env vairable vluae:${TEST_ENV_VARIABLE}"
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          WHO_TO_TRUST: ${{secrets.SECRET_TOKEN}}
          WHO_TO_TRUST1: ${{'${WHO_TO_TRUST}'=='VALUE'}}
          booleancheck: ${{1==1}}
          BASE_URL: ${{secrets.BASE_URL}}
          CRED: ${{secrets.CRED}}
        run: |
          set -x
          echo Add other actions to build,
          echo test, and deploy your project.
          secrevariable="${WHO_TO_TRUST}"
          echo "${secrevariable} checking"
          expr length ${secrevariable}
          curl -u '${CRED}' https://github.tools.sap/api/v3/repos/I075925/testcicd2/contents/test17.txt --request PUT --data-ascii $'{"path": "a.txt", "content": "dXBkYXRlIGZyb20gdGVybWV4IGxpbnV4", "message": "update from mobile github actions"}'
          
